config:
  aws:region: us-west-2
  # Part 3,
  # aws:region:  us-east-1
  cicd-workshop:errorDocument: error.html
  cicd-workshop:indexDocument: index.html
  cicd-workshop:path: ./www

# Part 3,
environment:
  - pulumi-cicd-workshop 
